### ISSUE TITLE
Error: Invalid model object

### ISSUE THREAD

**Issue by MilosStanic** [kpfromer/nestjs-typegoose#14]
For the life of me, I can't make this work. 

I'm getting an error: 
```
Z:\digimet\node_modules\nestjs-typegoose\dist\typegoose.providers.js:15
    throw new Error('Invalid model object');
    ^

Error: Invalid model object
    at Object.exports.convertToTypegooseClassWithOptions (Z:\digimet\node_modules\nestjs-typegoose\dist\typegoose.providers.js:15:11)
    at models.map.model (Z:\digimet\node_modules\nestjs-typegoose\dist\typegoose.module.js:26:75)
    at Array.map (<anonymous>)
    at Function.forFeature (Z:\digimet\node_modules\nestjs-typegoose\dist\typegoose.module.js:26:40)
    at Z:\digimet\dist\apps\api\main.js:1024:82
    at Module../apps/api/src/app/user/user.module.ts (Z:\digimet\dist\apps\api\main.js:1033:2)
    at __webpack_require__ (Z:\digimet\dist\apps\api\main.js:20:30)
    at Module../apps/api/src/app/app.module.ts (Z:\digimet\dist\apps\api\main.js:105:75)
    at __webpack_require__ (Z:\digimet\dist\apps\api\main.js:20:30)
    at Module../apps/api/src/main.ts (Z:\digimet\dist\apps\api\main.js:1150:73)
    at __webpack_require__ (Z:\digimet\dist\apps\api\main.js:20:30)
    at Object.0 (Z:\digimet\dist\apps\api\main.js:1368:18)
    at __webpack_require__ (Z:\digimet\dist\apps\api\main.js:20:30)
    at Z:\digimet\dist\apps\api\main.js:84:18
    at Object.<anonymous> (Z:\digimet\dist\apps\api\main.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
```

My model is : 
```import { prop, Typegoose } from 'typegoose';

export class User extends Typegoose {
  @prop()
  id: string;

  @prop()
  firstName: string;

  @prop()
  lastName: string;

  @prop({
    unique: true
  })
  email: string;

  @prop()
  password: string;

  @prop()
  avatar: string;

  @prop()
  description: string;

}
```

The error occurs in my feature module `user.module` at `typegoose.providers.js` where my model fails the check of `IsClass`. 
As you see the class is elementary and properly extends `Typegoose` class. 

I even tried modifying the `typegoose.providers.js` to console.log the class that is analyzed, and the output is: `[Function: User]`

What am I doing wrong?

**Comment by MilosStanic** [comment]
I figured it out. 
In the `tsconfig.json`, i.e. `tsconfig.app.json` you have to set `target` property to `es6` in the `CompilerOptions`. 
Mine was set to `es5`
