### ISSUE TITLE
how to add @exclude() of class-transformer into this library for Serialization purpose!

### ISSUE THREAD

**Issue by ManuRodgers** [kpfromer/nestjs-typegoose#16]

**Comment by kpfromer** [comment]
Could you provide more context for this issue?

**Comment by ManuRodgers** [comment]
![image](https://user-images.githubusercontent.com/33333844/59075434-cd1b1980-8913-11e9-94d7-0f542b7cfd0c.png)

Hello mate, something like above for Serialization purpose

**Comment by emjimadhu** [comment]
@kpfromer I am having the same question! Is it possible?

**Comment by wodka** [comment]
Would be quite interesting, right now if I try to add it only ends in the following error

```
RangeError: Maximum call stack size exceeded
    at new FastBuffer (buffer.js:79:1)
    at allocate (buffer.js:325:13)
    at fromObject (buffer.js:406:15)
    at Function.from (buffer.js:222:11)
    at TransformOperationExecutor.transform (/node_modules/class-transformer/TransformOperationExecutor.js:98:27)
    at _loop_1 (/node_modules/class-transformer/TransformOperationExecutor.js:232:45)
    at TransformOperationExecutor.transform (/node_modules/class-transformer/TransformOperationExecutor.js:260:17)
    at _loop_1 (/node_modules/class-transformer/TransformOperationExecutor.js:232:45)
    at TransformOperationExecutor.transform (/node_modules/class-transformer/TransformOperationExecutor.js:260:17)
    at _loop_1 (/node_modules/class-transformer/TransformOperationExecutor.js:232:45)
    at TransformOperationExecutor.transform (/node_modules/class-transformer/TransformOperationExecutor.js:260:17)
    at _loop_1 (/node_modules/class-transformer/TransformOperationExecutor.js:232:45)
    at TransformOperationExecutor.transform (/node_modules/class-transformer/TransformOperationExecutor.js:260:17)
    at _loop_1 (/node_modules/class-transformer/TransformOperationExecutor.js:232:45)
    at TransformOperationExecutor.transform (/node_modules/class-transformer/TransformOperationExecutor.js:260:17)
    at _loop_1 (/node_modules/class-transformer/TransformOperationExecutor.js:232:45)
```

**Comment by duro** [comment]
I was able to get this to work, I think what is needed is to set the default setting at the lass level, and then then use property decorators to override that default. Try:

```
@Include()
class UserEntity {
  id: number

  @Exclude()
  password: string
}
```

**Comment by dgutoryan** [comment]
@duro where is `@Include()` decorator?
