### ISSUE TITLE
Update to typegoose/typegoose v6 - TypeError: (intermediate value).setModelForClass is not a function

### ISSUE THREAD

**Issue by aidanmcdonagh22** [kpfromer/nestjs-typegoose#35]
Hi there, firstly i'd like to say thank you for the package it's great! but I updated my package today and am currently getting stuck with errors. I am getting a 

> TypeError: (intermediate value).setModelForClass is not a function

Error.  The full error is:

`[Nest] 23619   - 08/10/2019, 15:17:02   [ExceptionHandler] (intermediate value).setModelForClass is not a function +1ms
TypeError: (intermediate value).setModelForClass is not a function
    at InstanceWrapper.useFactory [as metatype] (/Users/aidanmcdonagh/Documents/KHIPU Documents/KHIPU Kloud/KHIPU Kloud Backend V2/khipu-kloud-server/node_modules/nestjs-typegoose/dist/typegoose.providers.js:20:58)
    at Injector.instantiateClass (/Users/aidanmcdonagh/Documents/KHIPU Documents/KHIPU Kloud/KHIPU Kloud Backend V2/khipu-kloud-server/node_modules/@nestjs/core/injector/injector.js:279:55)
    at callback (/Users/aidanmcdonagh/Documents/KHIPU Documents/KHIPU Kloud/KHIPU Kloud Backend V2/khipu-kloud-server/node_modules/@nestjs/core/injector/injector.js:74:41)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at Injector.resolveConstructorParams (/Users/aidanmcdonagh/Documents/KHIPU Documents/KHIPU Kloud/KHIPU Kloud Backend V2/khipu-kloud-server/node_modules/@nestjs/core/injector/injector.js:113:24)
    at Injector.loadInstance (/Users/aidanmcdonagh/Documents/KHIPU Documents/KHIPU Kloud/KHIPU Kloud Backend V2/khipu-kloud-server/node_modules/@nestjs/core/injector/injector.js:78:9)
    at Injector.loadProvider (/Users/aidanmcdonagh/Documents/KHIPU Documents/KHIPU Kloud/KHIPU Kloud Backend V2/khipu-kloud-server/node_modules/@nestjs/core/injector/injector.js:35:9)
    at async Promise.all (index 3)
    at InstanceLoader.createInstancesOfProviders (/Users/aidanmcdonagh/Documents/KHIPU Documents/KHIPU Kloud/KHIPU Kloud Backend V2/khipu-kloud-server/node_modules/@nestjs/core/injector/instance-loader.js:41:9)
    at /Users/aidanmcdonagh/Documents/KHIPU Documents/KHIPU Kloud/KHIPU Kloud Backend V2/khipu-kloud-server/node_modules/@nestjs/core/injector/instance-loader.js:27:13
    at async Promise.all (index 7)
    at InstanceLoader.createInstances (/Users/aidanmcdonagh/Documents/KHIPU Documents/KHIPU Kloud/KHIPU Kloud Backend V2/khipu-kloud-server/node_modules/@nestjs/core/injector/instance-loader.js:26:9)
    at InstanceLoader.createInstancesOfDependencies (/Users/aidanmcdonagh/Documents/KHIPU Documents/KHIPU Kloud/KHIPU Kloud Backend V2/khipu-kloud-server/node_modules/@nestjs/core/injector/instance-loader.js:16:9)
    at /Users/aidanmcdonagh/Documents/KHIPU Documents/KHIPU Kloud/KHIPU Kloud Backend V2/khipu-kloud-server/node_modules/@nestjs/core/nest-factory.js:82:17
    at Function.asyncRun (/Users/aidanmcdonagh/Documents/KHIPU Documents/KHIPU Kloud/KHIPU Kloud Backend V2/khipu-kloud-server/node_modules/@nestjs/core/errors/exceptions-zone.js:17:13)
    at NestFactoryStatic.initialize (/Users/aidanmcdonagh/Documents/KHIPU Documents/KHIPU Kloud/KHIPU Kloud Backend V2/khipu-kloud-server/node_modules/@nestjs/core/nest-factory.js:80:13)
error Command failed with exit code 1.`

I have about 9 classes which I am loading into my .forFeature() function and prior to that am importing my Typegoose forRootAsync Module. If you would like some more information please ask, thank you.

**Comment by guilhermegehres** [comment]
i'm facing this issue to, my workaround is make my model class extends from Typegoose exported by @typegoose/typegoose.
according this https://typegoose.github.io/typegoose/guides/migrate-to-6 Typegoose class is deprecated, so this is temporary fix.

**Comment by aidanmcdonagh22** [comment]
@guilhermegehres solved! for some reason Upgrading didn't work, remove the package and reinstall it and it will work perfectly. If you need help let me know!
