### ISSUE TITLE
Type Error: "function model(doc, fields, skipId) {...}" is not a valid Model! - Help

### ISSUE THREAD

**Issue by sir3mat** [kpfromer/nestjs-typegoose#387]
Hello everybody,
this is the first time I open a request on github,I hope not to make mistakes.
Someone could kindly explain to me what are the general causes that could generate a similar error?

```typescript
TypeError: "function model(doc, fields, skipId) {
      model.hooks.execPreSync('createModel', doc);
      if (!(this instanceof model)) {
        return new model(doc, fields, skipId);
      }
      const discriminatorKey = model.schema.options.discriminatorKey;

      if (model.discriminators == null || doc == null || doc[discriminatorKey] == null) {
        Model.call(this, doc, fields, skipId);
        return;
      }

      // If discriminator key is set, use the discriminator instead (gh-7586)
      const Discriminator = model.discriminators[doc[discriminatorKey]] ||
        getDiscriminatorByValue(model, doc[discriminatorKey]);
      if (Discriminator != null) {
        return new Discriminator(doc, fields, skipId);
      }

      // Otherwise, just use the top-level model
      Model.call(this, doc, fields, skipId);
    }" is not a valid Model!
    at addModelToTypegoose (D:\Projects\npm-packages\nestjs-auth_ALL\nestjs-auth\node_modules\@typegoose\typegoose\lib\typegoose.js:141:66)
    at Object.getModelForClass (D:\Project\npm-packages\nestjs-auth_ALL\nestjs-auth\node_modules\@typegoose\typegoose\lib\typegoose.js:78:12)
    at InstanceWrapper.modelFactory [as metatype] (D:\Project\npm-packages\nestjs-auth_ALL\nestjs-auth\node_modules\nestjs-typegoose\dist\typegoose.providers.js:22:58)
    at Injector.instantiateClass (D:\Project\npm-packages\nestjs-auth_ALL\nestjs-auth-test-app\node_modules\@nestjs\core\injector\injector.js:293:55)
    at callback (D:\Project\npm-packages\nestjs-auth_ALL\nestjs-auth-test-app\node_modules\@nestjs\core\injector\injector.js:77:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
---
_**Some application context...**_ 
I'm trying to create an npm package that defines an authentication module.
This module does not include a userModule for managing users but I want this to be resolved dynamically by the application using my library.
If I use the monorepo structure with the / apps folder and the / libs folder everything works, but if I create a normal nestJs app and install my npm package this error occurs.

### APP MODULES 

**AppAuthModule.ts**
```typescript
import { Global, Module } from '@nestjs/common';
import { AuthUsersService } from './auth-users.service';
import { SessionSerializer } from './session.serializer';
import { AuthenticationModule, IUsersService } from '@myLibrary/nestjs-auth';
import { UsersModule } from 'src/users/users.module';

@Global()
@Module({
  imports: [AuthenticationModule, UsersModule],
  providers: [
    { provide: IUsersService, useClass: AuthUsersService },
    SessionSerializer,
  ],
  exports: [IUsersService],
})
export class AppAuthModule {}

```

**AppModule.ts**
```typescript
@Module({
  imports: [
    UsersModule,
    ConfigModule.load(path.resolve(__dirname, 'config', '**/!(*.d).{ts,js}')),
    TypegooseModule.forRootAsync({
      inject: [ConfigService],
      useFactory: (config: ConfigService) => config.get('db.mongo'),
    }),
    AppAuthModule,
  ],
  controllers: [AppController],
  providers: [
    AppService,
    {
      provide: APP_FILTER,
      useClass: HttpExceptionsFilter,
    },
    {
      provide: APP_FILTER,
      useClass: MongoExceptionFilter,
    },
  ],
})
export class AppModule {}
```

**UserModule.ts**
```typescript
import { Global, Module } from '@nestjs/common';
import { UsersController } from './users.controller';
import { UsersService } from './users.service';
import { User } from './models/user.model';
import { TypegooseModule } from 'nestjs-typegoose';

@Module({
  imports: [TypegooseModule.forFeature([User])],
  controllers: [UsersController],
  providers: [UsersService],
  exports: [UsersService, TypegooseModule],
})
export class UsersModule {}

```

**BasicModel.ts**
```typescript
import { ApiPropertyOptional } from '@nestjs/swagger';
import { TimeStamps } from '@typegoose/typegoose/lib/defaultClasses';

export class BasicModelDto {
  @ApiPropertyOptional({ type: String, format: 'date-time' })
  createdAt?: Date;

  @ApiPropertyOptional({ type: String, format: 'date-time' })
  updatedAt?: Date;
}

export class BasicModel extends TimeStamps {
  createdAt: Date;

  updatedAt: Date;
}
```

**UserModel.ts**
```typescript
import { prop, index, pre } from '@typegoose/typegoose';
import * as bcrypt from 'bcrypt';
import * as mongoose from 'mongoose';
import { BasicModel } from 'src/baseCRUD/models/base.model';

@index({ email: 1 }, { unique: true })
@pre<User>('save', async function(next: mongoose.HookNextFunction) {
  try {
    if (!this.isModified('password')) {
      return next();
    }
    const hashed = await bcrypt.hash(this['password'], 10);
    this['password'] = hashed;
    return next();
  } catch (err) {
    return next(err);
  }
})
export class User extends BasicModel {
  @prop({ required: true })
  email!: string;

  @prop({
    required: [true, 'Password is required'],
    minlength: [4, 'Must be at least 4 characters'],
    select: false,
  })
  password!: string;

  @prop({ required: true, default: false })
  isSocial!: boolean;

  @prop({ required: true, default: 'local' })
  socialProvider!: string;

  @prop({ required: true, default: false })
  isValid!: boolean;
}

```
### NPM PKG MODULE 

**AuthModule.ts**
```typescript

import { Module, DynamicModule } from '@nestjs/common';
import { AuthenticationService } from './authentication.service';
import { PassportModule } from '@nestjs/passport';
import { LocalStrategy } from './strategies/local.strategy';
import { JwtModule } from '@nestjs/jwt';
import { JwtStrategy } from './strategies/jwt.strategy';
import { AuthenticationController } from './authentication.controller';
import { FacebookStrategy } from './strategies/facebook.strategy';
import { GoogleStrategy } from './strategies/google.strategy';
import { TypegooseModule } from 'nestjs-typegoose';
import { RefreshToken } from './models/refresh-token.model';
import { TokenService } from './token/token.service';
import { EmailVerification } from './models/email-verification.model';
import { AuthConstants } from './constants';
import { ForgottenPassword } from './models/forgotten-password.model';
import { EmailService } from './email/email.service';

@Module({
  imports: [
    PassportModule.register({
      session: true,
    }),
    JwtModule.register({
      secret: AuthConstants.jwtConstants.secret,
    }),
    TypegooseModule.forFeature([
      RefreshToken,
      EmailVerification,
      ForgottenPassword,
    ]),
  ],
  providers: [
    AuthenticationService,
    LocalStrategy,
    JwtStrategy,
    FacebookStrategy,
    GoogleStrategy,
    TokenService,
    EmailService,
  ],
  controllers: [AuthenticationController],
  exports: [
    AuthenticationService,
    LocalStrategy,
    JwtStrategy,
    FacebookStrategy,
    GoogleStrategy,
    TokenService,
    EmailService,
  ],
})
export class AuthenticationModule { }
```

**IUsersService.ts**
```typescript
import { SignupDto } from '../dto';
import { User } from './user.interface';
export const IUsersService = Symbol('IUsersService');
export interface IUsersService {
  findOneToValidate(email: string): Promise<User>;
  setPassword(email: string, newPassword: string): Promise<boolean>;
  findOne(filter: object): Promise<User>;
  findById(id: string): Promise<User>;
  create(item: SignupDto): Promise<User>;
  delete(id: string): Promise<User>;
  update(id: string, item: Partial<User>): Promise<User>;
  validateUser(username: string, pass: string): Promise<any>;
}
```

**BaseModel.ts**
```typescript
import { ApiProperty } from '@nestjs/swagger';
import { modelOptions, prop } from '@typegoose/typegoose';

@modelOptions({
  schemaOptions: {
    timestamps: true,
    toJSON: {
      virtuals: true,
      getters: true,
    },
  },
})
export abstract class BaseModel {
  @ApiProperty({ type: Date })
  @prop()
  createdAt?: Date; // provided by schemaOptions.timestamps
  @ApiProperty({ type: Date })
  @prop()
  updatedAt?: Date; // provided by schemaOptions.timestamps
  @ApiProperty({ type: String })
  _id?: string; // _id getter as string
}

```

**EmailVerificationModel.ts**
```typescript
import { prop } from '@typegoose/typegoose';
import { BaseModel } from './base.model';
import { IEmailVerification } from '../interfaces/email-verification.interface';
export class EmailVerification extends BaseModel implements IEmailVerification {
  @prop()
  email: String;
  @prop()
  emailToken: String;
  @prop()
  timestamp: Date;
}

```

**ForgottenPassword.ts**
```typescript
import { prop } from '@typegoose/typegoose';
import { BaseModel } from './base.model';
import { IForgottenPassword } from '../interfaces/forgotten-password.interface';
export class ForgottenPassword extends BaseModel implements IForgottenPassword {
  @prop()
  email: string;
  @prop()
  newPasswordToken: string;
  @prop()
  timestamp: Date;
}

```

**RefreshToken.ts**
```typescript
import { prop } from '@typegoose/typegoose';
import { BaseModel } from './base.model';
import { IRefreshToken } from './../interfaces/refresh-token.interface';

export class RefreshToken extends BaseModel implements IRefreshToken {
  @prop({ required: true, unique: true })
  value!: string;

  @prop()
  userId: string;

  @prop({ required: true })
  expiresAt: Date;

  @prop()
  clientId: string;

  @prop()
  ipAddress: string;
}

```

**Comment by sir3mat** [comment]
I fixed it temporarily using only nestjs/mongoose and typegoose
