### ISSUE TITLE
Can't resolve dependencies error

### ISSUE THREAD

**Issue by seekcx** [kpfromer/nestjs-typegoose#8]
Hi, I am using this module for the first time. It looks great, but my reference documentation didn't work properly after it was written.

**app.module.ts**

```ts
import { Module } from '@nestjs/common';
import { AppService } from './app.service';
import { AppController } from './app.controller';
import { TypegooseModule } from 'nestjs-typegoose';
import { ProfileModule } from './profile/profile.module';

@Module({
    imports: [
        TypegooseModule.forRoot('mongodb://localhost/user', {
            useNewUrlParser: true,
        }),
        ProfileModule,
    ],
    controllers: [AppController],
    providers: [AppService],
})
export class AppModule {}
```

**profile.model.ts**

```ts
import { prop, Typegoose } from 'typegoose';

export class Profile extends Typegoose {
    @prop({ required: true, unique: true })
    nickname: string;
}
```

**profile.module.ts**

```ts
import { Module } from '@nestjs/common';
import { ProfileService } from './profile.service';
import { TypegooseModule } from 'nestjs-typegoose';
import { ProfileController } from './profile.controller';

import { Profile } from './profile.model';

@Module({
    imports: [TypegooseModule.forFeature(Profile)],
    controllers: [ProfileController],
    providers: [ProfileService],
})
export class ProfileModule {}

```

**profile.service.ts**

```ts
import { ModelType } from 'typegoose';
import { Profile } from './profile.model';
import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';

@Injectable()
export class ProfileService {
    constructor(@InjectModel('profile') private readonly model: ModelType<Profile>) {}

    async findAll() {
        return await this.model.find();
    }
}
```

After executing the `npm start` command, an error was thrown:
```bash
⇢ npm start

> user@0.0.1 start /Users/abel/Desktop/develop/modules/user
> ts-node -r tsconfig-paths/register src/main.ts

[Nest] 10377   - 2018-9-17 13:23:12   [NestFactory] Starting Nest application...
[Nest] 10377   - 2018-9-17 13:23:12   [InstanceLoader] TypegooseModule dependencies initialized +22ms
[Nest] 10377   - 2018-9-17 13:23:12   [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 10377   - 2018-9-17 13:23:12   [ExceptionHandler] Nest can't resolve dependencies of the ProfileService (?). Please make sure that the argument at index [0] is available in the current context. +12ms
Error: Nest can't resolve dependencies of the ProfileService (?). Please make sure that the argument at index [0] is available in the current context.
    at Injector.lookupComponentInExports (/Users/abel/Desktop/develop/modules/user/node_modules/@nestjs/core/injector/injector.js:146:19)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
    at Function.Module.runMain (module.js:695:11)
    at Object.<anonymous> (/Users/abel/Desktop/develop/modules/user/node_modules/ts-node/src/bin.ts:157:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by seekcx** [comment]
it works! 🎉
